### ISSUE TITLE
cell barcode is automatically converted to a long number by seqc?

### ISSUE THREAD

**Issue by fulxie** [ambrosejcarr/seqc#320]
I got a single cell analysis result analyzed by seqc from a paper and found long number used for cell names. 
eg:
121270373903595
121270374157236
121270374414252
121270376480155
121270376741619
121270378384669

I want to ask if seqc could automatically convert cell barcode to a long number? Can I revert it back to a normal cell barcode ?

Thanks!

**Comment by ambrosejcarr** [comment]
Hi @fulxie,

Yes, you should be able to decode them back into barcodes using the encoders in this module: [seqc/blob/master/src/seqc/sequence/encodings.py](https://github.com/ambrosejcarr/seqc/blob/master/src/seqc/sequence/encodings.py)

**Comment by ambrosejcarr** [comment]
Yep, perfect. 👍  I'm going to close this issue, but please feel free to re-open it if you need further assistance.
